sudo: false

language: python

cache: pip

.mixins:
  - &xenial-mixin
    os: linux
    dist: xenial
    sudo: true

install:
  - pip install tox pyOpenSSL
  - make set-alpha-version

script:
  - tox

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=style
    - python: 3.6
      env: TOXENV=complexity
    - python: 3.6
      env: TOXENV=security

    - python: 2.7
      env: TOXENV=drf34-py27-django110
    - python: 2.7
      env: TOXENV=drf35-py27-django110
    - python: 2.7
      env: TOXENV=drf36-py27-django110
    - python: 2.7
      env: TOXENV=drf37-py27-django110
    - python: 2.7
      env: TOXENV=drf38-py27-django110
    - python: 2.7
      env: TOXENV=drf39-py27-django110
    - python: 2.7
      env: TOXENV=drf37-py27-django111
    - python: 2.7
      env: TOXENV=drf38-py27-django111
    - python: 2.7
      env: TOXENV=drf39-py27-django111

    - python: 3.4
      env: TOXENV=drf34-py34-django110
    - python: 3.4
      env: TOXENV=drf35-py34-django110
    - python: 3.4
      env: TOXENV=drf36-py34-django110
    - python: 3.4
      env: TOXENV=drf37-py34-django110
    - python: 3.4
      env: TOXENV=drf38-py34-django110
    - python: 3.4
      env: TOXENV=drf39-py34-django110
    - python: 3.4
      env: TOXENV=drf37-py34-django111
    - python: 3.4
      env: TOXENV=drf38-py34-django111
    - python: 3.4
      env: TOXENV=drf39-py34-django111
    - python: 3.4
      env: TOXENV=drf37-py34-django20
    - python: 3.4
      env: TOXENV=drf38-py34-django20
    - python: 3.4
      env: TOXENV=drf39-py34-django20

    - python: 3.5
      env: TOXENV=drf34-py35-django110
    - python: 3.5
      env: TOXENV=drf35-py35-django110
    - python: 3.5
      env: TOXENV=drf36-py35-django110
    - python: 3.5
      env: TOXENV=drf37-py35-django110
    - python: 3.5
      env: TOXENV=drf38-py35-django110
    - python: 3.5
      env: TOXENV=drf39-py35-django110
    - python: 3.5
      env: TOXENV=drf37-py35-django111
    - python: 3.5
      env: TOXENV=drf38-py35-django111
    - python: 3.5
      env: TOXENV=drf39-py35-django111
    - python: 3.5
      env: TOXENV=drf37-py35-django20
    - python: 3.5
      env: TOXENV=drf38-py35-django20
    - python: 3.5
      env: TOXENV=drf39-py35-django20
    - python: 3.5
      env: TOXENV=drf37-py35-django21
    - python: 3.5
      env: TOXENV=drf38-py35-django21
    - python: 3.5
      env: TOXENV=drf39-py35-django21

    - python: 3.6
      env: TOXENV=drf37-py36-django110
    - python: 3.6
      env: TOXENV=drf38-py36-django110
    - python: 3.6
      env: TOXENV=drf39-py36-django110
    - python: 3.6
      env: TOXENV=drf37-py36-django111
    - python: 3.6
      env: TOXENV=drf38-py36-django111
    - python: 3.6
      env: TOXENV=drf39-py36-django111
    - python: 3.6
      env: TOXENV=drf37-py36-django20
    - python: 3.6
      env: TOXENV=drf38-py36-django20
    - python: 3.6
      env: TOXENV=drf39-py36-django20
    - python: 3.6
      env: TOXENV=drf37-py36-django21
    - python: 3.6
      env: TOXENV=drf38-py36-django21
    - python: 3.6
      env: TOXENV=drf39-py36-django21

    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf37-py37-django110
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf38-py37-django110
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf39-py37-django110
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf37-py37-django111
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf38-py37-django111
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf39-py37-django111
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf37-py37-django20
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf38-py37-django20
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf39-py37-django20
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf37-py37-django21
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf38-py37-django21
    - <<: *xenial-mixin
      python: 3.7
      env: TOXENV=drf39-py37-django21
    - stage: deploy alpha version
      if: type != pull_request AND branch != master
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: Maximilien-R
        password:
          secure: M/RF3Lo5tB0lw1Whli3k8MLoPBQYF5v0rCiLsNqsvSIt/uy7AAIfL+zZs9Tkjo7wFVf5jACahBlVqcnmqlaKVKh++ep2SAUO4vCArIkNco2vqHV8TQTjc6wGKcZwC1GIRqNYnCM9XAUrq4sRE3Tcve4yMOGlirUG1zEn+ZS6J2Hbqk/jWJAfc9LT7r1gYkExWUItqhj6NxcN43wEsrvRwqM1cP2dJGC/tLQdK/mMDk6Cp6ODIYAKIzMOHjX87fUI6CzOsP4H4MdXGUPOfzciFWhdNoyC9I64xZwSil3KD8bY6mbsldh+zPiffYZEB1eRAzBeJpiQmFP6WjlexFFrg9LJiGBh1a06PiO1Rt4HdE1w+EmJBhA2Crh/l0O1x5cMooOZEXV4/ztlGCqQ1Js1MAaPY2uWwRoNENx8gVlovTDfL1bp9t75i69K+pXvHyHfYW+Q14OYb3yNfL2O2O6SumXmWJTysCQBc9rYo2YjrdQo6r09KHanA13w1leh+NmKX5FgT4ivZC3EN6W3tN3MYvt8cyv7fmYtC9CWWVARxgcQy4nn28A/cnheuQTQ1BseVfmhGPJNiXeKsr+pKSXRrR77Y6jP1+iT5HXnGdeBlBbuMCK3QDUQqN/f3Ro9wGSZ1YKurDmrI6A5MOmRnG68ZXbixg0x6gFaxA8e4IaEH2I=
        skip_cleanup: true
        on:
          all_branches: true
          condition: "$TRAVIS_BRANCH != master"
    - stage: deploy production version
      if: type != pull_request AND branch = master
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        user: Maximilien-R
        password:
          secure: dZWY19nbSYy18Fn30YF3rKag35AHWo+0vDCWhUZj2ZQpwbWqMpfD8RqBWej2R1+ccn2xfwJDHannRgwL/wIfmplVca1AVHanLgQzu/nRF4ZQlDx/1mlgG+/V7jxTeMoW9CPS/kRnRke8ArpczQMmjg8Ud0v8//SvQ01WuBkdomhRbDvMTHCYGpaNRDBUCPYXZLVnNyKIwb9cwqXNfO5ce75mDQn8Ye9gcE/6vAlXo/mEjNXGyQLBe8c24PKi469uSil99bGBFB3pA7taxizRb6ZL2quedMEDvw3aimwaUwBiK5kYkg40A2xpbVdj0mUdIVy4vReTCRN8IeyyRX/3YyO+lyfzxe6qL0NOzbYokpFfH+51HHjYU2LOvWw5Dt7/rrnpntlI/FJ4q/k3dUt+XtPA/lxAhpQVA/RHYGjyd+I//a6zAOO8b4gztz0wz/ug+/N7ZaZJ6hv8548xB2mXBH6JO9b39CBWc7LoeoUhhx5fT721SZn/jk5RSOsHsmH+Z0ow7gy/Wxa3ZzKj0KpY9GVp99GcntkdbVaHjaBjr1LArN/L8bRFG/2tWUGdAFo7LVHNy3kakY4MbLk+ZSG9FftmyzjOnc6r8k3Nz3ePEj94BgeD275Jq9RklZsQ2qOyBB9sY8OzgdS8oquRFKf6nqYi92Gl45y34D7Wpc3Fih4=
        skip_cleanup: true
        on:
          branch: master
          tags: true
