version: "3.6"

services:
  package: &package
    build: .

  package-volumes: &package-volumes
    <<: *package
    volumes:
      - .:/usr/src/app

  dev-package: &dev-package
    build:
      context: .
      args:
        - target=.[development]

  dev-package-volumes: &dev-package-volumes
    <<: *dev-package
    volumes:
      - .:/usr/src/app

  format-imports:
    <<: *dev-package-volumes
    command: isort -rc rest_framework_recaptcha/.

  check-format-imports:
    <<: *dev-package
    command: isort --check-only -rc rest_framework_recaptcha/.

  format:
    <<: *dev-package-volumes
    command: black -l 79 --py36 rest_framework_recaptcha

  check-format:
    <<: *dev-package
    command: black -l 79 --py36 --check rest_framework_recaptcha

  style:
    <<: *dev-package
    command: flake8 rest_framework_recaptcha

  complexity:
    <<: *dev-package
    command: xenon --max-absolute B --max-modules A --max-average A rest_framework_recaptcha

  test-unit:
    <<: *dev-package
    command: py.test -s tests/unit -vv --cov . --cov-config .coveragerc --cov-report term-missing --cov-report xml:reports/coverage.xml --cov-report html:reports/coverage.html
    volumes:
      - ./reports:/usr/src/app/reports

  test-all:
    <<: *dev-package
    command: tox

  security-sast:
    <<: *dev-package
    command: bandit -r rest_framework_recaptcha/.

  build-docs:
    <<: *dev-package-volumes
    command: /bin/bash -c "sphinx-apidoc -o docs/ rest_framework_recaptcha && make -C docs clean && make -C docs html"

  bumpversion-package:
    <<: *dev-package-volumes
    command: [ "bumpversion", "${VERSION_PART-patch}" ]

  build-package:
    <<: *package-volumes
    command: python setup.py sdist bdist_wheel

  publish-test-package:
    <<: *dev-package-volumes
    command: twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  publish-package:
    <<: *dev-package-volumes
    command: twine upload dist/*

  generate-translations:
    <<: *package-volumes
    command: /bin/bash -c "cd rest_framework_recaptcha && django-admin makemessages --locale=${LOCALE}"

  update-translations:
    <<: *package-volumes
    command: /bin/bash -c "cd rest_framework_recaptcha && django-admin makemessages --all"

  compile-translations:
    <<: *package-volumes
    command: /bin/bash -c "cd rest_framework_recaptcha && django-admin compilemessages"
